export const serviceCatalogItems = {
  password_reset: {
    title: "Password reset",
    category: "Identity",
    priority: "high",
    agent: "Access Agent",
    summary: "Verify identity, reset password, rotate sessions, and notify the employee.",
    prompt: "Who needs the reset, which identity provider is affected, and how was identity verified?",
    confidence: 94,
    status: "triaging",
  },
  app_access: {
    title: "App access request",
    category: "Onboarding",
    priority: "medium",
    agent: "Onboarding Agent",
    summary: "Validate requester, check access scope, route approvals, and provision selected apps.",
    prompt: "Which app, user, access level, business reason, and manager approval are involved?",
    confidence: 88,
    status: "approval_required",
  },
  employee_onboarding: {
    title: "Employee onboarding",
    category: "Onboarding",
    priority: "high",
    agent: "Onboarding Agent",
    summary: "Create onboarding ticket for app bundle, identity setup, device readiness, and audit trail.",
    prompt: "Employee name, start date, department, manager, app bundle, and device needs.",
    confidence: 90,
    status: "triaging",
  },
  vpn_troubleshooting: {
    title: "VPN troubleshooting",
    category: "Network",
    priority: "high",
    agent: "Network Agent",
    summary: "Collect device posture, inspect gateway status, propose workaround, and verify connection.",
    prompt: "Location, device type, error message, affected users, and connection time.",
    confidence: 82,
    status: "triaging",
  },
  contractor_deactivation: {
    title: "Contractor deactivation",
    category: "Security",
    priority: "critical",
    agent: "Security Agent",
    summary: "Pause for approval, scan ownership dependencies, revoke access, and document completion.",
    prompt: "Contractor name, last day, owned systems, repositories, API keys, and approving manager.",
    confidence: 74,
    status: "approval_required",
  },
} as const;

export type ServiceCatalogKey = keyof typeof serviceCatalogItems;
